name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image if commit contains 'fix'
      if: contains(github.event.head_commit.message, 'fix')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vmq-itchat:latest

    - name: Skip Docker build and push if commit does not contain 'fix'
      if: "!contains(github.event.head_commit.message, 'fix')"
      run: echo "Commit message does not contain 'fix', skipping Docker build and push."